# .github/workflows/build.yml
name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip build-essential git openjdk-11-jdk
          pip install --upgrade pip
          pip install buildozer cython

      # Accept the Android SDK licenses automatically
      - name: Accept Android SDK licenses
        run: |
          mkdir -p "$ANDROID_HOME/licenses" || true
          echo -e "\n24333f8a63b6825ea9c5514f83c2829b004d1fee\n" > "$ANDROID_HOME/licenses/android-sdk-license"
          echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd\n" > "$ANDROID_HOME/licenses/android-sdk-preview-license"

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3  # Ensure you're using the latest version
        with:
          name: apk
          path: bin/*.apk
